### ISSUE TITLE
responseObserver.complete() is not called

### ISSUE THREAD

**Issue by christian-schlichtherle** [cloudnc/observable-webworker#116]
https://github.com/cloudnc/observable-webworker/blob/f5fe0499ad2ec98dacee2183497fa4e1b9b6bbc1/projects/observable-webworker/src/lib/from-worker.ts#L15

First, thanks for this useful library. When using it for a single web worker, I noticed that my web worker never completes and I had to insert a call to `take(1)` into its pipeline. Looking at your source code, I believe the reason is that `responseObserver.complete()` is never called in the `fromWorker` function - see link.

For the full picture:

Expectation: If I use `fromWorker` and give it an observable which completes after emitting N events as input and use a one-to-one transformation (e.g. the identity function), then the output observable should complete after emitting N events, too.

Actual behavior: The output observable never completes.

Workaround: Insert `take(N)` into the pipeline on the worker side.

**Comment by zakhenry** [comment]
@christian-schlichtherle I might be missing something here, but I'm fairly sure that the code should be causing the worker to terminate after the input observable has terminated. This is the behaviour observed in the [demo site](https://cloudnc.github.io/observable-webworker/) too - a `fromWorker` call is used to hash a file and then the worker terminates once there is no further input.

Are you sure that your input observable is completing?

**Comment by christian-schlichtherle** [comment]
Yes, because I'm only using `of(item)` to create an observable which completes after the given `item`.

For reference, please have a look at my PR - it adds the missing call to `responseObservable.complete()`.

**Comment by christian-schlichtherle** [comment]
Also, I'm using `concatMap` on the worker side to transform the single input item into a large (but not infinite) number of output items. Maybe this specific transformation exposes the bug?!

**Comment by maxime1992** [comment]
Right after your `concatMap`, try to put a `finalize` with a console.log to make sure that the observable finishes.
I suspect it may not but could be wrong. Hard to debug and understand without code.
If you could create a minimal repro Stackblitz of the issue using `of` and `concatMap` that'd be ideal.

**Comment by christian-schlichtherle** [comment]
Here's a simple test case:

In `engine-worker.ts`:
```typescript
import { DoWork, runWorker } from 'observable-webworker'
import { concatMap, finalize, interval, map, Observable, take, takeWhile } from 'rxjs'

export type EngineConfig = {
  limit: number
  rate: number
}

class EngineWorker implements DoWork<EngineConfig, string> {
  public work(config$: Observable<EngineConfig>): Observable<string> {
    return config$.pipe(
      take(1), // FIXME: The resulting observable never finishes without this call!
      concatMap((config) => {
        const gen = (function* double(): Generator<number> {
          for (let i = 1; i <= config.limit; i++) {
            yield 2 * i
          }
        })()
        return interval(1000 / config.rate).pipe(
          map(() => gen.next().value),
          takeWhile((item) => item),
          finalize(() => console.log('OVER!'))
        )
      })
    )
  }
}

runWorker(EngineWorker)
```

In `renderer.ts`:
```typescript
import { fromWorker } from 'observable-webworker'
import { of, Subscription } from 'rxjs'
import { EngineConfig } from './engine-worker'

const engineWorkerFactory = (): Worker => {
  return new Worker(new URL('./engine-worker', import.meta.url), {
    type: 'module'
  })
}
fromWorker<EngineConfig, number>(engineWorkerFactory, of({ limit: 30, rate: 30 })).subscribe({
  next(item): void {
    console.log(item)
  },
  complete(): void {
    console.log('OVER AND OUT!')
  }
})
```

If you run this unchanged, it will print:

```
2
[...]
60
OVER!
OVER AND OUT!
```

This is because I put the workaround `take(1)` into the pipeline on the worker side. However, if you remove this, it will omit the final "OVER AND OUT!" message because the output stream never completes. If you take a closer look at my PR, introducing the call `responseObservable.complete()` should fix the issue. Calling this method or `.error(error)` is part of the interface contract for an `Observable`.

**Comment by maxime1992** [comment]
Thanks for the example. Bug confirmed with a live [repro on stackblitz](https://stackblitz.com/edit/stackblitz-starters-isyem1?file=src%2Fmain.ts).

**Comment by maxime1992** [comment]
Ok I've got a test highlighting the issue 

![image](https://github.com/cloudnc/observable-webworker/assets/4950209/db50b4d3-e31b-4b4c-addb-8b684b49c8ca)

I'll write a fix as well
