### ISSUE TITLE
How to debug Observable Worker Class in DevTools

### ISSUE THREAD

**Issue by Smurf81** [cloudnc/observable-webworker#12]
Hello,

i can't access inside Observable Worker Class when debugging in devtools, just have 
```
module.exports = __webpack_public_path__ + "0.worker.js"
```
Without observable-webworker, i have no problem

**Comment by zakhenry** [comment]
@Smurf81 can you please clarify specifically what you're trying to achieve? 

Debugging workers can be a little more difficult than regular main thread stuff as you can't easily look up the file as it's not available in sources until used, however when I want to hit breakpoints I just use the `debugger` keyword in my source code which quickly gives me a reference to the file to add other breakpoints

**Comment by Smurf81** [comment]
Thanks for your advice, it works.
