### ISSUE TITLE
Support request: Getting error on fresh Angular 10 project

### ISSUE THREAD

**Issue by msegmx** [cloudnc/observable-webworker#48]
I'm trying to setup the simple 'hello-worker' example, but I'm getting an error that just logs an event to console:

Stackblitz: 

`ERROR Event {isTrusted: true}`

Local: 
`core.js:4081 ERROR Event {isTrusted: true, type: "error", target: Worker, currentTarget: Worker, eventPhase: 0, …}`

Stackblitz can be found here: [https://stackblitz.com/edit/angular-ivy-cxfqta](https://stackblitz.com/edit/angular-ivy-cxfqta)

Help please.

**Comment by zakhenry** [comment]
Hi @msegmx does this issue happen for you locally as well as stackblitz? I'm not sure that stackblitz is able to compile webworkers, so it might just be that.

**Comment by msegmx** [comment]
I created a new project but forgot to create a web-worker with "ng g web-worker...".
It works now as expected.

Thanks for quick reply!

**Comment by zakhenry** [comment]
nice one! do you think it would help to have some better documentation in this repo's readme?

**Comment by msegmx** [comment]
I wanted to try it on a blank app before integrating your library (which is great btw) into my actual project. I totally forgot to add web-worker support first. Would it have helped if the documentation had mentioned it in the "install" section (for Angular apps)? Well, probably yes, but again, I wasn't thinking. (I haven't had coffee yet) :)

I think the documentation is well-written and detailed enough, so it's not a must.

Thanks for this library!
