### ISSUE TITLE
is it possible to access sqlite api's with webworker

### ISSUE THREAD

**Issue by jothipandiyanjp** [cloudnc/observable-webworker#50]
I am using webworker in angular based electron application.
I am trying to check whether we can access sqlite API using webwoker or not?
https://www.npmjs.com/package/sqlite3
https://www.npmjs.com/package/capacitor-sqlite

**Comment by zakhenry** [comment]
Hi @jothipandiyanjp - this webworker library currently only supports [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) which are a browser-only feature. Given browsers cannot (and should not) make database connections, you will not be able to connect to an sqlite db with this library.

If you're on a node.js platform you might be after worker threads, which would be interesting to add to this library, or possibly fork and restructure as a sibling library

**Comment by zakhenry** [comment]
Closing as I think this is not an issue with the library itself
