### ISSUE TITLE
Failed to parse source map: "ng:/observable-webworker/lib/from-worker.ts" URL is not supported

### ISSUE THREAD

**Issue by CP-Ram** [cloudnc/observable-webworker#52]
Hi,
I am using angular v10.
After upgraded from angular9 to v10 getting warning on console with `--prod` build

`"observable-webworker": "^3.2.4"`

**Warning:**
`WARNING in ./node_modules/observable-webworker/__ivy_ngcc__/fesm5/observable-webworker.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/observable-webworker/lib/from-worker-pool.ts" URL is not supported`

Is there anything affect with Ivy compiler?

**Comment by zakhenry** [comment]
Hey @CP-Ram I've not spotted this issue and we did recently upgrade to Angular 10 at CloudNC without any issues with this lib. Can you provide a reproduction repo?

While this library is compiled using ng-packagr, it doesn't actually use any angular features so I don't see how ivy could affect it.

**Comment by CP-Ram** [comment]
Not sure it's the actual case or not but after deleted `node_modules` ,`package-lock.json` , `npm cache clean --force ` and again installed npm through `npm install` warning got disappeared for me.
thanks.

**Comment by zakhenry** [comment]
Huh strange, I've had some issues with the files that ngcc outputs into node modules not working an indeed starting node modules from fresh fixes it. Bizarre, thanks the followup
