### ISSUE TITLE
Not compatible with Angular 12 & Webpack 5 --prod build (required update)

### ISSUE THREAD

**Issue by lincolnthree** [cloudnc/observable-webworker#67]
Hello, first, thanks for this awesome library!

Angular 12 is forcing an upgrade to Webpack 5 (it is no longer optional), and this package does not seem to be compatible with the latest update -- upgrading has resulted in 100% reproducibly broken web-workers --- https://github.com/angular/angular-cli/releases/tag/v12.0.0-next.9 (angular cli release notes regarding Webpack forced upgrade)

I have created a minimal reproduction that demonstrates the various issues I have not been able to solve. I've tried various attempts at getting the syntax working, but so far nothing has.

Depending on the syntax used, `fromWorker` either silently fails entirely, or throws strange errors attempting to communicate with its workers.

Any thoughts about this? I can't seem to find a good reason why this doesn't work, and the error messages are super vague (or at least I am not familiar enough to understand them).

### Reproduction steps:

```
git clone git@github.com:lincolnthree/example-webworker-broken-angular.git
git checkout observable-webworker
npm i
ng serve --prod
# open localhost:4200
# open dev tools and observe failures
```

### App code:
```

    const input$ = new Subject<string>();

    /*
     * 1. This syntax results in code that never seems to be called/never resolves.
     */
    const getWorkerFailsSilently = () => new Worker(new URL('./app.worker', import.meta.url), { type: 'module' });
    fromWorker(getWorkerFailsSilently, input$, null, {
      terminateOnComplete: true
    })
      .subscribe({
        complete: () => console.log('1. getWorkerFailsSilently COMPLETE'),
        error: error => console.error('1. getWorkerFailsSilently', error),
        next: msg => console.warn('1. getWorkerFailsSilently', msg)
      });


    /*
     * 2. This syntax results in code that gets called but results in an error.
     */
    const getWorkerFailsWithError = () => {
      const url = new URL('./app.worker', import.meta.url);
      const worker = new Worker(url, { type: 'module' });
      return worker;
    };
    fromWorker(getWorkerFailsWithError, input$, null, {
      terminateOnComplete: true
    })
      .subscribe({
        complete: () => console.log('2. getWorkerFailsWithError COMPLETE'),
        error: error => console.error('2. getWorkerFailsWithError', error),
        next: msg => console.warn('2. getWorkerFailsWithError', msg)
      });

    /*
     * 3. This syntax results in code that gets called but results in an error (expected since it's not using 'type: "module"').
     */
    const getWorkerFailsWithErrorNoModule = () => {
      const url = new URL('./app.worker', import.meta.url);
      const worker = new Worker(url);
      return worker;
    };
    fromWorker(getWorkerFailsWithErrorNoModule, input$, null, {
      terminateOnComplete: true
    })
      .subscribe({
        complete: () => console.log('3. getWorkerFailsWithErrorNoModule COMPLETE'),
        error: error => console.error('3. getWorkerFailsWithErrorNoModule', error),
        next: msg => console.warn('3. getWorkerFailsWithErrorNoModule', msg)
      });

    input$.next('Hello world!');
```

### Worker code:

```
/// <reference lib="webworker" />

import { DoWork, ObservableWorker } from 'observable-webworker';
import { Observable, of } from 'rxjs';
import { switchMap } from 'rxjs/operators';

@ObservableWorker()
export class ExampleWorker implements DoWork<string, string> {

  constructor() {
    console.warn('Created worker');
  }

  public work(input$: Observable<string>): Observable<string> {
    return input$.pipe(
      switchMap(input => {
        console.warn('Worker received message:', input)
        return of('message from worker: ' + input);
      })
    );
  }

}

```

### Messages in console:

```
Angular is running in development mode. Call enableProdMode() to enable production mode.
16:56:12.386 localhost/:1 Refused to execute script from 'http://localhost:4200/dca7a459b5ae24595be1.ts' because its MIME type ('video/mp2t') is not executable.
16:56:12.386 app.component.ts:61 3. getWorkerFailsWithErrorNoModule Event {isTrusted: true, type: "error", target: Worker, currentTarget: Worker, eventPhase: 2, …}
error @ app.component.ts:61
__tryOrUnsub @ Subscriber.js:183
error @ Subscriber.js:135
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
worker.onerror @ observable-webworker.js:50
wrapFn @ zone.js:803
ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ core.js:28619
ZoneDelegate.invokeTask @ zone.js:433
Zone.runTask @ zone.js:205
ZoneTask.invokeTask @ zone.js:516
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
error (async)
customScheduleGlobal @ zone.js:1808
ZoneDelegate.scheduleTask @ zone.js:421
onScheduleTask @ zone.js:311
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:248
Zone.scheduleEventTask @ zone.js:274
(anonymous) @ zone.js:1965
desc.set @ zone.js:864
rxjs__WEBPACK_IMPORTED_MODULE_8__.Observable.pipe.kind.kind @ observable-webworker.js:50
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ map.js:16
subscribe @ Observable.js:23
call @ dematerialize.js:9
subscribe @ Observable.js:23
AppComponent @ app.component.ts:59
AppComponent_Factory @ app.component.ts:66
getNodeInjectable @ core.js:3549
instantiateRootComponent @ core.js:10102
createRootComponent @ core.js:12463
create @ core.js:25102
bootstrap @ core.js:29573
(anonymous) @ core.js:29286
_moduleDoBootstrap @ core.js:29286
(anonymous) @ core.js:29256
ZoneDelegate.invoke @ zone.js:400
onInvoke @ core.js:28632
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ core.js:28619
ZoneDelegate.invokeTask @ zone.js:433
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
ZoneAwarePromise.then @ zone.js:1466
bootstrapModule @ core.js:29281
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.js:597
(anonymous) @ main.js:598
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.js:599
webpackJsonpCallback @ jsonp chunk loading:33
(anonymous) @ main.js:1
Show 23 more frames
16:56:12.399 index.js:52 [WDS] Live Reloading enabled.
16:56:12.405 dca7a459b5ae24595be1.ts:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "video/mp2t". Strict MIME type checking is enforced for module scripts per HTML spec.
16:56:12.405 app.component.ts:44 2. getWorkerFailsWithError Event {isTrusted: true, type: "error", target: Worker, currentTarget: Worker, eventPhase: 2, …}
error @ app.component.ts:44
__tryOrUnsub @ Subscriber.js:183
error @ Subscriber.js:135
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
worker.onerror @ observable-webworker.js:50
wrapFn @ zone.js:803
ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ core.js:28619
ZoneDelegate.invokeTask @ zone.js:433
Zone.runTask @ zone.js:205
ZoneTask.invokeTask @ zone.js:516
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
error (async)
customScheduleGlobal @ zone.js:1808
ZoneDelegate.scheduleTask @ zone.js:421
onScheduleTask @ zone.js:311
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:248
Zone.scheduleEventTask @ zone.js:274
(anonymous) @ zone.js:1965
desc.set @ zone.js:864
rxjs__WEBPACK_IMPORTED_MODULE_8__.Observable.pipe.kind.kind @ observable-webworker.js:50
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ map.js:16
subscribe @ Observable.js:23
call @ dematerialize.js:9
subscribe @ Observable.js:23
AppComponent @ app.component.ts:42
AppComponent_Factory @ app.component.ts:66
getNodeInjectable @ core.js:3549
instantiateRootComponent @ core.js:10102
createRootComponent @ core.js:12463
create @ core.js:25102
bootstrap @ core.js:29573
(anonymous) @ core.js:29286
_moduleDoBootstrap @ core.js:29286
(anonymous) @ core.js:29256
ZoneDelegate.invoke @ zone.js:400
onInvoke @ core.js:28632
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ core.js:28619
ZoneDelegate.invokeTask @ zone.js:433
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
ZoneAwarePromise.then @ zone.js:1466
bootstrapModule @ core.js:29281
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.js:597
(anonymous) @ main.js:598
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.js:599
webpackJsonpCallback @ jsonp chunk loading:33
(anonymous) @ main.js:1
Show 23 more frames
```

### Versions:

```
sharktop:example-web-worker lincoln$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0-next.9
Node: 14.15.0
OS: darwin x64

Angular: 12.0.0-next.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0-next.9
@angular-devkit/build-angular   12.0.0-next.9
@angular-devkit/core            12.0.0-next.9
@angular-devkit/schematics      12.0.0-next.9
@angular/cdk                    12.0.0-next.7
@schematics/angular             12.0.0-next.9
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by lincolnthree** [comment]
Related: https://github.com/cloudnc/observable-webworker/issues/62

**Comment by lincolnthree** [comment]
Comment from Angular team on the issue I filed with them: https://github.com/angular/angular-cli/issues/20553#issuecomment-821524841

**Comment by zakhenry** [comment]
Hey thanks for the detailed issue report and followup with Angular team, I'll take a look into this this afternoon. It is certainly a puzzling issue..

**Comment by lincolnthree** [comment]
@zakhenry Thanks, I appreciate your efforts. And yeah, I've really spent a lot of time on this and this is the best I've been able to do so far. I think I've exhausted my expertise, hence... this issue :/

**Comment by lincolnthree** [comment]
Oh, and an even stranger factoid. In my actual application (not the sample repo), the code seems to work using non-prod builds and the syntax from `syntax flavor 2` above. But when building for production, everything breaks and shows the behavior of the sample app.

**Comment by zakhenry** [comment]
One thing I'm curious about; do you have a `tsconfig.worker.json` in your root directory or has Angular done away with this for webpack 5? What gets generated when you run `ng generate web-worker app` ?

**Comment by lincolnthree** [comment]
I do. It should be in the sample repo. Is it not there?

**Comment by zakhenry** [comment]
Oh I'm sorry I didn't notice you provided an example repo, even better!

**Comment by lincolnthree** [comment]
Actually I think I forgot to include it! Ack!! Hang tight.

**Comment by lincolnthree** [comment]
Here you go: https://github.com/lincolnthree/example-webworker-broken-angular/tree/observable-webworker 

Can't believe I forgot that! I think I pasted it in then overwrote it as I kept adding to the description of the issue.

**Comment by lincolnthree** [comment]
Yeah I don't know what happened to the original issue description. Here are the repro steps that are also missing:

```
git clone git@github.com:lincolnthree/example-webworker-broken-angular.git
git checkout observable-webworker
npm i
ng serve
# open localhost:4200
# open dev tools and observe failures
```

**Comment by lincolnthree** [comment]
Oh, actually it's there now. Weird. Wasn't showing up in the other tab. Ok I'm going to stop spamming now ;P

**Comment by zakhenry** [comment]
Hey I took a quick look and was able to get it to work by commenting out attempts #2 & #3. I'm not entirely sure what was going on with them interfering with the first one, but perhaps once worker initialization fails, all bets are off for that worker.

To get the complete event to fire in the worker you need a `take(1)` after the switchMap, otherwise the outer observable never completes and the worker doesn't shut down.

**Comment by zakhenry** [comment]
Here's the diff if it helps https://github.com/lincolnthree/example-webworker-broken-angular/pull/1/files

**Comment by lincolnthree** [comment]
Interesting. That's very odd because I started with the first example, which should just silently fail. Worker should never initialize.

You're saying it actually returns a value? I assume that was with normal `ng serve` right? Not prod mode?

Did you try running `ng serve --prod`.

I'll take another look when I wake up tomorrow.

**Comment by lincolnthree** [comment]
Wait, are you saying the `take(1)` in the worker is necessary to return any results/messages back to the main thread? Or just the complete event?

I assume this isn't the case, but just clarifying.

**Comment by zakhenry** [comment]
Oh sorry I had missed the distinction that there was a difference in behaviour with local/prod. I had a look into this too now and found an interesting thing - the minifier was completely stripping out the content of the worker, this explains the silent failure as there was nothing listening on the other end (observable-webworker is as lean/performant as possible so it doesn't do any startup checks). 

I'm not entirely sure what is wrong with the decorator approach, I guess the minifier is being too aggressive and assumes the class can't be doing anything.

Luckily there is a workaround which is to use the `runWorker` function as outlined in https://github.com/cloudnc/observable-webworker#important-note

I'll add a commit to my MR to show this approach, which is working with `--prod` mode.

I'll dig into this more deeply separately (keep this issue open please), and update observable-webworker to document this new behaviour with webpack 5 (including the `new Worker(new URL('./app.worker', import.meta.url), { type: 'module' })` syntax.


---

to your second comment:

> Wait, are you saying the take(1) in the worker is necessary to return any results/messages back to the main thread? Or just the complete event?

just the complete event

> I would assume the worker could be terminated by closing the observable on either side, no?

you are correct

I just added the `take(1)` in because I saw your test subscription was checking for the completion, so wanted to make sure my fix covered that case

**Comment by lincolnthree** [comment]
> Oh sorry I had missed the distinction that there was a difference in behaviour with local/prod. 
It's my fault. I forgot to mention that.

>  The minifier was completely stripping out the content of the worker
Oof, good catch! I should have checked for that.

> Luckily there is a workaround which is to use the `runWorker `function
Fantastic! This is a fine workaround. Not quite as pretty -- I quite like your annotation syntax -- but certainly no trouble.

> I just added the take(1) in because I saw your test subscription was checking for the completion, so wanted to make sure my fix covered that case

Ah yes, good thinking. I wasn't even worried about that event, but I added it to see if that was somehow firing when the others were not. If it were completing before anything happened, etc.

Also, I confirmed using `runWorker` is a workaround here as well! Seems this does result in workers that actually do work :)

Thanks again for your fantastic work. This library is a huge help. (As is your attention to it.)

**Comment by lincolnthree** [comment]
@zakhenry An update on this. It looks like the workaround has only partly solved the issue. It seems like something is still going wrong on Safari browser, but it's not consistent. (The best kind of problem.)

This time it happens in both dev mode AND prod mode.

About half the time or less, the Web Worker will silently fail to load and I'll see this in the network panel:

![image](https://user-images.githubusercontent.com/362329/115465212-423c2300-a1fc-11eb-82eb-c1eff452e9da.png)

![image](https://user-images.githubusercontent.com/362329/115465371-80d1dd80-a1fc-11eb-9dd5-0c477f7e591b.png)

I'm trying to get more useful info. Let me know if you think of anything I should look for to resolve this. It really seems like some kind of Webpack issue where it's trying to load modules but failing to produce valid content.

**Comment by lincolnthree** [comment]
Hang on. This might be a different issue. The worker does seem to be getting invoked. Digging a bit more.

**Comment by zakhenry** [comment]
Oh no :(

I'm curious why it is trying to download a file just for the node_module - I would have thought like the demo that it would bundle the worker dependencies into a single worker file. It kinda looks like the worker is trying to dynamically load the dependencies?

**Comment by lincolnthree** [comment]
I'm also curious why it's downloading a file as well, which is why I still suspect something weird.

**Comment by lincolnthree** [comment]
@zakhenry Ok false alarm, sorry for the noise. I think this is actually an IndexedDB bug - the downloading of the Worker source file appears to be working, regardless of how strange it is. I don't know why it does the on *every* call, the call is never returning.

**Comment by lincolnthree** [comment]
@zakhenry That said, I think this issue may have been uncovered because it looks like the workers are being executed twice for some reason, which is causing deadlocks in Safari's "amazing" implementation of IndexedDB.

![image](https://user-images.githubusercontent.com/362329/115469305-613db380-a202-11eb-899c-7580cb3e9a33.png)

**Comment by lincolnthree** [comment]
Logging an error from the Constructor reveals .... I'm not sure what... possibly `tslib` involvement as well?:

![image](https://user-images.githubusercontent.com/362329/115469874-6818f600-a203-11eb-983e-f6994b247ecd.png)

**Comment by lincolnthree** [comment]
Oh god. I figured it out. Adding `runWorker` without removing the `@ObservableWorker()` annotation is of course going to result in double execution because the type information is preserved and your library does what it does best with annotations.

Removing that resolved the double invocation issue.

**Comment by zakhenry** [comment]
Hey @lincolnthree thank for updating with your resolution, I've updated the readme with details from your findings to help out the next person that is using Webpack 5. I'm intending to move this repo to Angular 12, but will wait for general release

**Comment by lincolnthree** [comment]
Thanks @zakhenry! Again, I really truly appreciate your help with this issue. I would not have been able to figure this out. Thanks again for supporting such a great tool.

**Comment by zakhenry** [comment]
Thanks for the kind words @lincolnthree 😁  

As ever, I'm curious about how people are using observable-webworker, and peeking at your profile it sounds like TopDecked might have a really interesting use-case. If you can and feel like it, feel free to share in the discussion I just created at #69
