### ISSUE TITLE
[Question]: Is it possible to use this library in an Angular library? 

### ISSUE THREAD

**Issue by jamesbarrett95** [cloudnc/observable-webworker#77]
Hi there,

Using web workers in a Angular library doesn't seem to be supported by the Angular team at the moment.

I had a look at [this GitHub issue ](https://github.com/maxime1992/demo-webworker-library/blob/master/projects/fibonacci-webworker/src/lib/fibonacci.ts)and there are a couple of suggestions, [one of which is quite involved](https://github.com/angular/angular-cli/issues/15059#issuecomment-747419154), but looks to be a short-term solution whilst the Angular team (hopefully) work on something built-in.

However, the solution described above involves splitting apart the instantiation of the worker and the implementation detail, whereas the observable-webworker library must couple these together. 

So my question is: Do you think it's possible to use this library in an Angular library? If so, how would you recommend implementing it? 

I understand it's a big ask, especially considering Angular doesn't have any documentation around web workers in libraries! I shall be trying to find a solution in the mean time.

P.S. thanks a lot for this library! I struggled with trying to work with observables with the native worker but it was incredibly difficult. This library has made it a lot easier.

**Comment by maxime1992** [comment]
Hi @jamesbarrett95 it is possible to use webworker in libraries but it's a little of a "hack" for now as it's not supported natively.

The trick is to declare it at the app level and provide it through DI. I've explained how to do so in depth in this comment: https://github.com/angular/angular-cli/issues/15059#issuecomment-747419154
