### ISSUE TITLE
Running Karma tests does not executes our webworker

### ISSUE THREAD

**Issue by ArgV04** [cloudnc/observable-webworker#83]
When running karma unit-tests for a service or component which includes **fromWorker( () => PATH)** flow. The worker never get called. Is there any additional setup needed to get this run?

We are using Angular 13.

It looks like runWorker() <-- is never get called, which is defined in the worker file like your webpack 5 sample shows.

**Comment by zakhenry** [comment]
Hi @ArgV04 can you provide a minimal repro of this? I can't see any reason why karma might be any different to running locally

**Comment by zakhenry** [comment]
Closing as stale, feel free to update with a repro and I'll reopen :)
