### ISSUE TITLE
Broken in Dev & Canary Chrome Builds

### ISSUE THREAD

**Issue by lincolnthree** [cloudnc/observable-webworker#91]
Please be advised: [https://bugs.chromium.org/p/chromium/issues/detail?id=1078821](https://bugs.chromium.org/p/chromium/issues/detail?id=1078821)

Error: `Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost/default-node_modules_observable-webworker_fesm2015_observable-webworker_mjs.js' failed to load.`

The above bug WILL break this package (and any use of Worker in production WebPack apps) if it is not fixed before affected Chrome Dev & Canary builds get to the production / stable branch. ***It does not appear to be a bug in the `observable-webworker` package at this time. I do not know if there are any workarounds.***

I noticed this broke because I run Canary WebView on my mobile phone. Just trying to call attention to this so that anyone here who depends on Workers actually working will be able to maybe bring some more priority to the issue over at Chromium. Please add any feedback you have to that issue.

As a quick summary, this bug affects Workers that call `importScripts()` and are loaded from `localhost` or constructed from a data/`Blob` URL.

Please help out and star / vote for this issue in the Chromium bug tracker. Thank you! And for anyone else who comes here looking for why Workers are broken, this is why.

**Comment by zakhenry** [comment]
@lincolnthree tracking the upstream issue, it kinda looks like this may no longer be a problem? Hard to say as there was no official response but I reckon we can close this for now?

**Comment by lincolnthree** [comment]
Yeah that seems fair to do. Closing for now. Thanks!
