### ISSUE TITLE
Angular 13: Error event is only fired

### ISSUE THREAD

**Issue by LuigiDC** [cloudnc/observable-webworker#94]
Hi iam getting actually an error by calling the lib out of my project.
<img src="https://user-images.githubusercontent.com/7841854/153937378-911f4a9a-d195-4969-ad29-003efc9f21b7.png" width="600" height="300">

and on ng serve
`Warning: C:/Users/dicarm99/planning-tool/src/app/service/worker-thread/release-planning.worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.`

Actually i cant resolve where the problems is. **_Is angular 13 supported_**?

**_### Here my steps:_**

My setup (based on the todos and readme's):

### Component
Implementing the service called by a button press:
<img src="https://user-images.githubusercontent.com/7841854/153938388-e1e97fc0-ae59-41a7-b1ad-f30bb75a7674.png" width="435" height="154">
<img src="https://user-images.githubusercontent.com/7841854/153938205-799c0083-7c48-4770-9ac4-21d9a91a6940.png" width="435" height="254">

### Service
My service and the worker are located in the same directory:
<img src="https://user-images.githubusercontent.com/7841854/153938134-3f18326c-2a80-4cf9-a11d-6da00b571954.png" width="435" height="304">

### My Worker
<img src="https://user-images.githubusercontent.com/7841854/153938067-db8ac0f3-5f68-4537-85ee-227f24c37b96.png" width="480" height="320">

The command for initializing the env with 
`ng g web-worker /service/worker-thread/releasePlanning`
 
added to **_angular.json_**:
`"webWorkerTsConfig": "tsconfig.worker.json"`

and the **_tsconfig.worker.json_**:
`{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/worker",
    "lib": [
      "es2018",
      "webworker"
    ],
    "types": []
  },
  "include": [
    "src/**/*.worker.ts"
  ]
}`

System details:

System Info

-  OS: Windows 10
-  Node Version: v16.13.2
-  Frameworks: Angular 13.2.0
-  rxjs: 7.5.2

**Comment by zakhenry** [comment]
Hi @LuigiDC I can confirm Angular 13 is supported (the demo linked on the main page is using Angular 13).

It appears that your worker import syntax is using the legacy webpack version, instead of the newer URL based version that is now required for webpack 5.

You need to change your service to the following

```ts
// ...
() => new Worker(new URL('./release-planning.worker', import.meta.url), { type: 'module' }),
// ...
```

Hope that sorts it for you!

p.s. I realised from your question that the readme wasn't clear and had a couple of errors so I've tidied that up in #95

**Comment by LuigiDC** [comment]
@[zakhenry](https://github.com/zakhenry) Thanks a lot. That was the solution. Yes the documentation was kind of confusing.
I tried in some of my attemps the newer URL version out, but had the syntax wrong, too.

Thanks a lot for your fast response.
Now everything is working as expected.

Kind regards.
